### ISSUE TITLE
Mention that copy is easier to copy/paste in certain PDF viewers than in others

### ISSUE THREAD

**Issue by ricky1981** [balinterdi/rarwe-issues#118]
When using Preview on Mac, copying the code examples is a real pain, frequently I end up with the line numbers in the code and even selecting the correct lines can be unreliable.

Also, it would be good to make it clearer when the code is supposed to be added. There are code examples included that are actually not supposed to be copied in but it's not always obvious. Maybe add a title in the code block like "Add this code"?

**Comment by balinterdi** [comment]
Adding a label that makes it clear it has to be copied is a great idea, I'll come up with something.

As for making it easier to copy/paste code from the pdf, do you have something in mind about how I could make it easier? Not having line numbers would probably facilitate it but they are useful in some instances. I'll play around with it but let me know if you have an idea. Thank you.

**Comment by ricky1981** [comment]
It seems to be a weird issue with Preview, I've switched to Adobe Reader
and selecting/copying works as you would expect. Maybe just pop a note
early in the book, could be a lot easier than trying to work out the logic
Preview uses! :)

**Comment by balinterdi** [comment]
Thank you for verifying this, I'll add a note.

**Comment by balinterdi** [comment]
Hey Ricky,

I've tried this myself (on a Mac) and it's equally easy to copy both from Preview (8.1) and from Adobe Reader (11.0.13). First is Preview, second is Reader:

![screen shot 2015-10-24 at 21 06 20](https://cloud.githubusercontent.com/assets/5022/10712184/3348759c-7a93-11e5-8e72-d037e1eb69bf.png)
![screen shot 2015-10-24 at 21 06 27](https://cloud.githubusercontent.com/assets/5022/10712187/387e56a8-7a93-11e5-80bc-fd02d7c6f0bb.png)

Anyway, I'll still leave a note in the book, I'm just curious to see when it is really broken. Here, when you paste, the indentation is gone, but otherwise it's fine (no line numbers, for example).
