### ISSUE TITLE
Fix Bootstrap layout issue

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#160]
I am having an layout issue as described in the document. I am not able to resolve it. Hope someone can guide me. Thanks.

[rarwe-layout-issue.pdf](https://github.com/balinterdi/rarwe-issues/files/116845/rarwe-layout-issue.pdf)

**Comment by balinterdi** [comment]
There was actually a Bootstrap layout issue starting in this chapter. I've fixed it and it will go live in the next book updates but in the meantime here is what needs to change:

Add a wrapping div with class `row` to the outlet:

```handlebars
<!-- app/templates/application.hbs -->
<div class="container">
  <div class="page-header">
    <h1>Rock & Roll<small> with Ember.js</small></h1>
  </div>
  <div class="row">
    {{outlet}}
  </div>
</div>
```

Remove the `row` class in the `bands` template so that it looks like this:

```hbs
<!-- app/templates/bands.hbs -->
<div class="list-wrapper">
  <ul class="list-group">
    {{#each model.sortedContent as |band|}}
      <li class="list-group-item">{{band.name}}</li>
    {{/each}}
  </ul>
</div>
```

And remove the `row` class in the `bands.band.songs` template so that it looks like this:

```handlebars
<!-- app/templates/bands/band/songs.hbs -->
<ul class="list-group songs">
  {{#each model.songs as |song|}}
    <li class="list-group-item song">
      {{song.title}}
      <span class="rating pull-right">{{song.rating}}</span>
    </li>
  {{/each}}
</ul>
```

Thank you for bringing up this issue.
