### ISSUE TITLE
Bootstrap issue in application.hbs

### ISSUE THREAD

**Issue by gokulk13** [balinterdi/rarwe-issues#161]
In page 38, I think, the bootstrap class col-md-6 in application.hbs must not be there as it will occupy only half of container and `col-md-12` may do the best.

![balint](https://cloud.githubusercontent.com/assets/15158776/12909036/ff754ada-cf22-11e5-88bb-1b7d3df38f86.png)

**Comment by zzr994** [comment]
Nice catch. This was the issue that I was facing in #160 (layout issue) which no one responded to.  This solves my layout problem. I knew that the view port needed to be stretched out, but could not figure out how to do it. Not being familiar with bootstrap, I thought it would be in the container class.  I never found time to investigate. Thanks for pointing this out.   I am wondering how others got it to work.

**Comment by gokulk13** [comment]
It can be accomplished by replacing the `col-md-6` to  `col-md-12` 12 is the full width of the container in bootstrap.

can refer to this for Bootstrap Grid system.

http://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=two-column-grid-layouts-for-tablets-and-desktops

**Comment by zzr994** [comment]
Yes, that is what I did.  Replaced col-md-6 with col-md-12.

**Comment by balinterdi** [comment]
I'm not completely certain but I think I used `col-md-6` because I wanted the whole column to be more narrow in the initial chapters. I have to double-check, though, which I'll do later this week.

**Comment by lscoates** [comment]
@balinterdi I just purchased the book today and on page 38 of the PDF, I don't see any of the above code (my application template is just the UL. Is this an issue with the PDF or due to the version that I got?

<img width="634" alt="screen shot 2016-02-18 at 4 16 45 pm" src="https://cloud.githubusercontent.com/assets/2301097/13162664/0a90e08e-d65b-11e5-966b-874d475ecf17.png">

**Comment by gokulk13** [comment]
@lscoates I meant 38 as the PDF page number, **not the number shown by the PDF reader**. You have snapshotted the PDF at page **31**

![image issue](https://cloud.githubusercontent.com/assets/15158776/13166629/da52ba74-d6ef-11e5-83d8-eb8d7f0e74d1.png)

**Comment by balinterdi** [comment]
@lscoates @gokulk13 The first time this appears is on page 44 ("real" page number, the one in the footer) in the Routing chapter.

I'm not sure whether this is to be fixed as it will make the whole container half as wide as there is space and I don't see it as a huge problem, even more so because we'll overhaul it in the next chapter, Nested routes.

@zz994 Your issue (#160) is in the next chapter, Nested routes and I'm going to inspect that separately now.

If nobody has a strong opinion against this, I'm going to close this one, but I'll leave it open for a few days so that you have time to respond.

**Comment by gokulk13** [comment]
@balinterdi imo, no issues, the following lessons may overwrite the file...

**Comment by lscoates** [comment]
@gokulk13 Ahh okay cool, that makes more sense. I was just kind of confused because in Ch 3 we add in Bootstrap and suddenly all this new style appears without any reference.

**Comment by balinterdi** [comment]
@lscoates Right, this is already fixed and will go out in the next update but let me copy here what you need to add after you installed `ember-bootstrap`:

```handlebars
<!-- app/templates/application.hbs -->
<div class="container">
  <div class="row list-wrapper push-down-m">
    <div class="col-md-6">
      <ul class="list-group songs">
        {{#each songs.sortedContent as |song|}}
          <li class="list-group-item">
            {{song.title}} by <em>{{song.band}}</em>
            <span class="rating pull-right">{{song.rating}}</span>
          </li>
        {{/each}}
      </ul>
    </div>
  </div>
</div>
```

```css
/* app/styles/app.css */
.list-wrapper {
  margin-left: 0;
  margin-right: 0;
}

.push-down-m {
  margin-top: 50px;
}

.songs .rating {
  color: #aaa;
  font-size: 1.1em;
}
```

Is this what you meant by "suddenly all this new style appears without any reference"?

**Comment by lscoates** [comment]
@balinterdi Yes! Thank you so much :smile:
