### ISSUE TITLE
No diff signs for application.hbs in nested routes chapter

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#170]
There are no diff signs in the **nested routes** chapter `application.hbs` file listing. The **introduction to ember.js** chapter says they will appear "where it facilitates comprehension," so this may be intentional.

**Comment by balinterdi** [comment]
Yes, it is intentional in this case. It's oftentimes a tough decision between using diffs or not and when the content of the file in question is relatively short and the diff would not be straightforward to interpret to humans, I tend to go with showing the whole thing there, without diffs.

I am aware that this might also be a matter of taste and if you think in some case it would make way more sense to go one way or another, please let me know.

**Comment by balinterdi** [comment]
In this case it's 

```handlebars
<!-- app/templates/application.hbs -->
<div class="container">
  <div class="page-header">
    <h1>Rock & Roll<small> with Ember.js</small></h1>
  </div>
  <div class="row">
    {{outlet}}
  </div>
</div>
```

against

```handlebars
<!-- app/templates/application.hbs -->
<div class="container">
  <div class="page-header">
    <h1>Rock &amp; Roll<small> with Ember.js</small></h1>
  </div>
  <div class="row">
-    <div class="col-md-6">
-      <nav class="navbar navbar-default" role="navigation">
-        <div class="collapse navbar-collapse">
-          <ul class="nav navbar-nav">
-            <li>{{link-to "Bands" "bands"}}</li>
-            <li>{{link-to "Songs" "songs"}}</li>
-          </ul>
-        </div>
-      </nav>
-    </div>
    {{outlet}}
    </div>
  </div>
</div>
```

With an explanation for the first case to ease the transition:

> The navbar from the previous chapter needs to go, since we are going to
radically change the routes of our application, and the simple `songs`
route will be no more. Just delete the `<nav>` tag and the `col-md-6`
wrapper div. It should now look like this:

To be honest, I'm really not sure which is clearer in this case :)
