### ISSUE TITLE
chapter 4 routing page 40

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#184]
On the page 40(chapter 4 - routing) is stated:

> The application template is rendered with the proper links in the header. Clicking on them will take us to the
> 'bands' or 'songs' routes, respectively. However, the lists are still not rendered on either of the pages.
> 

This is not exactly true from my expirience.
Following book instruction in that point I can open songs when clicking on songs:
[http://i.imgur.com/2yBPopS.png](http://i.imgur.com/2yBPopS.png)

This could be fixed in the book.

**Comment by balinterdi** [comment]
Could you describe the problem in more detail? You write that songs can be opened by clicking on the Songs link? You cannot do the same for Bands?

**Comment by gar** [comment]
@balinterdi I think it is the line "the lists are still not rendered" which is causing confusion.

If you are following along at this point in the book you haven't removed `app/routes/application.js` and that is defining a model with three `Song`s in it. Therefore when you click the "Songs" or "Bands" URL, the route seems to be finding the model from the application route and trying to render that. (It obviously only works for the Songs route because the model only contains song objects, as can be seen in @gandra's screenshot, but the Bands route displays a three element list with no text in it.)

I think either removing the line "the lists are still not rendered" on page 40 or else telling the user to `rm app/routes/application.js` before that line would make this clearer.

This wasn't a major issue for me, but it was a bit of a WTF moment! 😃

**Comment by balinterdi** [comment]
Gar, thank you very much for tracking this down, this is the thing that must have confused @gandra, too (I agree it can lead to some head-scratching). I've now modified the wording so that I don't state nothing is rendered in either of the lists.
