### ISSUE TITLE
On page 68 songs not appears - tipo/bug on page 63 activated on page page 68

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#187]
This what is stated on page 68 will not be true:
[http://i.imgur.com/2tzpfmG.png](http://i.imgur.com/2tzpfmG.png)

unless you fix the code from page 63:
[http://i.imgur.com/YpvDygk.png](http://i.imgur.com/YpvDygk.png)

**Comment by balinterdi** [comment]
Your image links give 404s, could you paste the images here? (just drag&drop them in the body of your comment box). Thank you.

**Comment by scervera** [comment]
I spent hours trying to get the songs to display. I tried @gandra fix that adds `.get('songs') to the end of the return statement in the songs.js route and it worked.

**Comment by balinterdi** [comment]
@scervera I took a look at this again and I don't see why the solution in the book wouldn't work. The route is currently like as follows:

```js
// app/routes/bands/band/songs.js
import Route from '@ember/routing/route';

export default Route.extend({
  model: function() {
    return this.modelFor('bands.band');
  }
});
```

This returns the band designated in the URL (you can even delete the route altogether as it implements the default behavior, returning the model of the parent route). The template then goes through *its songs* and displays each of them (note the `model.songs` in the `#each` helper):

```hbs
<!-- app/templates/bands/band/songs.hbs -->
<ul class="list-group songs">
  {{#each model.songs as |song|}}
    <li class="list-group-item song">
      {{song.title}}
      <span class="rating pull-right">{{song.rating}}</span>
    </li>
  {{/each}}
</ul>
```

Your solution could also work. You already return the songs in the model hook (thus `model` in the template becomes the array of songs and then you `{{#each}}` through `model` (instead of `model.songs`, as in the solution of the book.

The above route and template code are on page 61 and 66, respectively, in the latest 2.x release of the book (2018014).

**Comment by scervera** [comment]
I just found my error. My `{{#each}}` statement was incorrect. I had 
`{{#each model as |song|}}`
instead of:
{{#each model.songs as |song|}}

My mistake. Thanks for the detailed explanation. Great book!

**Comment by balinterdi** [comment]
Good, I'm closing this.
