### ISSUE TITLE
Chapter 8 : Controllers : ObjectController & ArrayController

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#192]
This is not an issue.  I am just looking for information.

I am looking at some legacy code which has ObjectController and ArrayController.
In Ember 2.0 both these controllers are deprecated and hence the chapter on the controllers does not have any reference to these.

Looking at the legacy code,  the controller for the template was able to  delegate the computed properties lookup to a ObjectController (via itemController). This seems to be very powerful because of the reusability of the ObjectController.

It will be nice if the book can cover some historical aspects of these deprecated controllers.  What problems did it solve or did not solve. Why were they deprecated.  I keep hearing that the controllers will give way to routable components. Is this the only reason. As these controllers are deprecated, how should we re-think (or refactor) in the Ember 2.0 way to support the functionality that these controllers supported.

Thanks.

**Comment by balinterdi** [comment]
The main thing these controllers were supported was proxying to the underlying model, an object (in the case of the ObjectController) and an array of objects (in the case of the ArrayController).

That saved some writing but introduced a layer of magic, and also made it difficult to refactor templates. In a recent project, I was quite delighted to realize that if the controller's model changes, I know exactly where to look for locations to refactor in the template as they all start with `model`. With proxying controllers this would have been a lot more error prone.

Regarding itemControllers, they also caused a lot of confusion (besides some nice tricks you can pull off with them) and I think that's eventually the reason they had to go. I haven't found the need for either proxying or item controllers ever since and the development experience (at least mine) was improved. It's quite easy to use simple components instead of item controllers for most tasks.

Mostly based on feedback, I'm planning to cut down on the historical sections as they can derail the flow of explanation. I created an Appendix in the last release that contains additional information, some of which are historical. It might make sense to have a section about proxying controllers but they get less and less relevant every day as they were removed a long time ago already.

**Comment by zzr994** [comment]
Thanks for the information.
