### ISSUE TITLE
p. 105 - Chapter 8 - Duplicate <button> tag

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#205]
On page 105, in the code sample from app/templates/bands/band/songs.hbs, the `<button>` tag is included twice. Lines 9-11 are exact duplicates of lines 6-8, and would produce an extra button if included.

**Comment by balinterdi** [comment]
Hey Andy,

Could you make a screenshot of this error? I looked on pg. 105 and in the entirety of Chapter 8 but couldn't find the double button include you mention.

![screen shot 2016-08-14 at 14 42 20](https://cloud.githubusercontent.com/assets/5022/17649149/5b7c5592-622d-11e6-8650-3c67b5f00e45.png)

Which does not mean it's not there, of course :)

Thank you.

**Comment by andyhelmsworth** [comment]
Perhaps it's on a different page of the iteration of your book I have. Attached is a screenshot. It's easy to miss because the disabled/action helpers are in reverse order on the sequential button tags. Let me know if you need higher rez.
![p105](https://cloud.githubusercontent.com/assets/14791023/17761748/b3efd6e8-64be-11e6-96a0-225a19403dcc.JPG)

**Comment by balinterdi** [comment]
That's weird because there is no duplication in "my" version:

![screen shot 2016-08-18 at 06 25 05](https://cloud.githubusercontent.com/assets/5022/17762035/c48c59b0-650c-11e6-9935-ae9f15e56ac3.png)

 but the last time I modified this snippet in the book was 2016-03-23 so I did not recently fixed this, either.

What does the first line in the Preface tell in your pdf? For me, it's "You are reading version 20160708 of this book).

**Comment by andyhelmsworth** [comment]
Just updated with a fresh download. The old version doesn't have that line in the preface, but the filename is rock-and-roll-with-emberjs-20160503.pdf. My new download lists '20160708' in the preface. Closing this as it's fixed in new version.
