### ISSUE TITLE
Ember CLI Route Generator creating Components instead of Templates

### ISSUE THREAD

**Issue by carterdea** [balinterdi/rarwe-issues#215]
In the Routing section, it asks us to run these commands:
```
$ ember generate route bands
$ ember generate route songs
```

It says that it will add 2 routes to `app/router.js` and it will add `app/routes/bands.js` &  `app/routes/songs.js` & `app/templates/bands.hbs` & `app/templates/songs.hbs`, but it didn't do any of that. All it did was add `app/components/bands.js` &  `app/templates/components/bands.hbs` (and the equivalent songs files).

This is my version:
```
ember-cli: 2.7.0
node: 5.2.0
os: darwin x64
```

Let me know if I'm doing something wrong!

**Comment by balinterdi** [comment]
Hey Carter,

That is indeed very strange. I just double-checked what happens if I generate a new route and it works as it should (and the way I describe in the book):

```
✓ ~/code/balinterdi/emberjs/rarwe-book/rarwe » ember generate route artists                                                                                                                                                   develop 7c7b1f0
installing route
  create app/routes/artists.js
  create app/templates/artists.hbs
updating router
  add route artists
installing route-test
  create tests/unit/routes/artists-test.js
```

It's very strange that *components* were generated when you explicitly asked for a route to be generated.

Does this happen in other Ember projects, too, or only in RARWE?

You might try reinstalling `ember-cli` from scratch, as described for Ember CLI releases (e.g [here](https://github.com/ember-cli/ember-cli/releases/tag/v2.7.0)).
