### ISSUE TITLE
Test for 'undefined' necessary with empty database

### ISSUE THREAD

**Issue by portugaleren** [balinterdi/rarwe-issues#235]
When you start the app on an empty database 'band' will be undefined and an error sent to the console so the typeof test is necessary in routes/bands.

  actions: {
    didTransition: function() {
      var band = this.modelFor('bands.band');
      if (typeof band !== 'undefined') {
        document.title = `${band.get('name')} songs - Rock & Roll`;
      }
    },

**Comment by balinterdi** [comment]
I think the case you describe occurs when you start the app on a URL for which the designated band is missing (like `/bands/4/songs` where the band with id 4 is missing). An empty database is a more restrictive case of this.

It's true that the app will misbehave (although I get a 404 from the API, not the error you describe above) in this case but since there is currently no way to  delete bands, this is not a big issue, in my opinion.

Is that the error you described? If not, could you describe it in more detail, possibly including screenshots? Thank you.

**Comment by portugaleren** [comment]
The error was was shown in the console when I started the app on an empty database i Firebase. The var 'band' was undefined as nothing could be assigned to it. My test for 'undefined' fixed the problem. I don't have a screenshot of it and can't recreate just now as I have data in the database. It's not a big issue but as an old mainframe developer I'm used to run a test like that.

**Comment by balinterdi** [comment]
At which point (which page) is this on? I think this can be produced *before* we hook up the app to the real-backend. (Once the app sends out ajax requests, it will hit the 404s I got)

**Comment by portugaleren** [comment]
It on page 133 in the PDF where you set up the descriptive page title and I added the test in the didTransition function

**Comment by balinterdi** [comment]
Ok, that makes sense then. I'll modify the content to tackle this case, either by modifying the code or just making a comment since this is really a corner-case and I don't want to add code which might make the general case less comprehensible.
