### ISSUE TITLE
Components- star-rating.hbs

### ISSUE THREAD

**Issue by Sabron13** [balinterdi/rarwe-issues#238]
Not sure why, but when I typed this out myself it left out the empty stars...

![rarwe-star-rating hbs](https://cloud.githubusercontent.com/assets/6323652/22229349/2484d6de-e1a5-11e6-8c0a-4c7a5c367f6a.png)

Still not sure what error I made, but maybe the plus signs in the margins would help?

**Comment by balinterdi** [comment]
By "left out the empty stars" you mean they weren't even rendered, so you only saw the full stars? In that section, I start with the template (the code snippet above) and only then I implement the component code (which has the `stars` property), so make sure you have that in place. You probably do, because otherwise no stars would be rendered at all but I want to make sure.

I did not use the plus signs because everything is new in this template file, this is the first time we're touching it.

**Comment by Sabron13** [comment]
Sorry, I meant to close this. It was a spelling error. Maybe I need checked for dyslexia lol.

thanks for getting back to me, I'm really loving the book.

**Comment by balinterdi** [comment]
Great, love to hear the book serves you well!
