### ISSUE TITLE
Make relocation of file more explicit

### ISSUE THREAD

**Issue by samrose** [balinterdi/rarwe-issues#282]
On page 85 we

```ember generate route songs```
which leaves us with routes/songs.js

The file ends up here on page 246:

``` javascript
// app/routes/bands/band/songs.js
export default Route.extend({
   (...)
+  resetController(controller) {
+    controller.setProperties({
+      isAddingSong: false,
+      newSongTitle: ''
+    });
+  },
});
```
Excerpt From: Balint Erdi. “Rock and Roll with Ember.js 3 (version: 20180302).”

...so I am suggesting to put in some language or explicit indication that this file needs to move. While it is obvious from the comment in the code, novice learners may not see this detail.

**Comment by balinterdi** [comment]
The `songs` route is a short-lived one that is only used in the "Chapter 4: Routing" and then removed at the end of "Chapter 5: Nested routes" in the "The roadie says" section.

The `bands.band.songs` route is created manually in Chapter 5 and then the above code snippet is added to it in Chapter 8: Advanced routing on page 136.

So, unless I'm missing something, we're not relocating a file, we deleted one and created another and added new content to it.

I understand it might be confusing that they are both a "songs" route (although the second one is a deeply nested one) so I'd like to hear what was confusing about it so that I can improve it.

**Comment by samrose** [comment]
@balinterdi I will review it again and report back here. Could have just been my newby-ish-ness with Ember in this case.
