### ISSUE TITLE
css .rr-inline-form-row vs .rr-form-inline-row

### ISSUE THREAD

**Issue by officeguy** [balinterdi/rarwe-issues#355]
fyi, there seems to be variation between:
page 255:
rr-form-inline-row 

vs:
page 285
rr-inline-form-row

**Comment by balinterdi** [comment]
Sorry about this, this had been fixed in the latest update that went out on Friday.

Both places now use the `rr-form-row-inline` class, to mix things up a bit ;)

<img width="1244" alt="screenshot 2018-11-18 at 21 35 03" src="https://user-images.githubusercontent.com/5022/48677766-fc398b80-eb79-11e8-8df0-f56ff744ae42.png">

**Comment by officeguy** [comment]
👍
