### ISSUE TITLE
p190 rating=rating -> rating=song.rating

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#375]
The code snippet on p190 is truncated, so I used it as an exercise!

I ended up with

`await render(hbs`{{star-rating rating=song.rating onClick=(action "updateRating" song)}}`);`

Using rating=rating as shown in the visible bit of the code snippet didn't work (nor could I understand why it might, as rating is a property of song), so I think there's an error even ignoring the truncation.

**Comment by balinterdi** [comment]
Great catch, thank you.

It has worked because the test doesn't assert whether the correct rating is shown when rendering the component. It only checks whether the rating is updated to the new value when triggering the `onClick` action. The test is still confusing works and I've fixed it (both in code and in the book).
