### ISSUE TITLE
p193 runloop could use some explanation

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#376]
The run() call in the stub model test created on p193 seems arcane - why can't we just call store.createRecord() directly, and why haven't we needed to use run() for previous tests?

Reading the Ember model test documentation (https://guides.emberjs.com/release/testing/testing-models/) just directs me to a general explanation of the run loop (https://guides.emberjs.com/release/applications/run-loop/) but leaves me none the wiser as to why model tests need to be run via the runloop.

**Comment by balinterdi** [comment]
True, and again, great catch.

In Ember versions <3.4 (I think, it was a relatively new version for sure) `Ember.set`s needed to be wrapped in `run()` because they automatically started a run loop (so that mutations can be properly observed) and that wasn't allowed in the testing environment (it was auto-started in non-tests environments).

This need was removed in Ember 3.4 so I removed it from the book (and the code).

**Comment by balinterdi** [comment]
Here's a very well written Discourse post (it could be an article) that explains why `run` is (was) needed and other details of tasks/microtasks/the runloop:

https://discuss.emberjs.com/t/readers-questions-why-does-ember-still-use-rsvp/14736

**Comment by edsnowden** [comment]
Fab, thanks, I'll have a gander at that.

BTW ember generate model-test band doesn't create the unit test stub file in my setup. I'm sure it's a local issue but thought I'd mention it in case something's changed.
