### ISSUE TITLE
p230 model hook is completely removed

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#386]
The second code snippet completely removes the model hook whereas we should only be removing the wait(). Also, the wait delay shown is 20000 whereas the value we added on p226 was 3000.

**Comment by edsnowden** [comment]
Incidentally - there is an appreciable delay after the spinner disappears and the data appears, because the Ajax call doesn't start until the spinner disappears. I realise it's just a demo but I wonder if reversing the promises (i.e. awaiting the Ajax call and returning the wait, or somehow arranging for them to happen simultaneously) would make for a smoother demo.

**Comment by balinterdi** [comment]
Thanks also for this.

> Incidentally - there is an appreciable delay after the spinner disappears and the data appears, because the Ajax call doesn't start until the spinner disappears.

The loading template is rendered while the promise returned from the model hook is not resolved. In the case of the `bands` route (which I've now tested) that means that the loading template is still rendered – and the spinner is displayed – while the network request is under way.

```js
async model() {
  await wait(3000); // takes 3 seconds 
  return this.store.findAll('band'); // takes ~2 seconds (let's say)
}
// total time while the loading template is rendered: 5 seconds
```

The explicit wait is only inserted so that the spinner is perceivable. If the network request returned "too fast", the user might not notice it.
