### ISSUE TITLE
p297 custom validator stub file looks different

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#406]
After running `ember g validator year-of-formation` the generated stub js file doesn't look like the one in the book. My guess would be you've accidentally pasted in the code for a description validator?

```
// app/validators/year-of-formation.js
import BaseValidator from 'ember-cp-validations/validators/base';

const YearOfFormation = BaseValidator.extend({
  validate(/*value, options, model, attribute*/) {
    return true;
  }
});

YearOfFormation.reopenClass({
  /**
   * Define attribute specific dependent keys for your validator
   *
   * [
   * 	`model.array.@each.${attribute}` --> Dependent is created on the model's context
   * 	`${attribute}.isValid` --> Dependent is created on the `model.validations.attrs` context
   * ]
   *
   * @param {String}  attribute   The attribute being evaluated
   * @param {Unknown} options     Options passed into your validator
   * @return {Array}
   */
  getDependentsFor(/* attribute, options */) {
    return [];
  }
});

export default YearOfFormation;
```

**Comment by edsnowden** [comment]
On p299 I can see we're using it to validate the band description field, so perhaps it makes sense to call the validator Description rather than YearOfFormation. However, on p299 we also do
```
     validator('year-of-formation')
```
which presumably relies on the validator class being called YearOfFormation?

**Comment by balinterdi** [comment]
Thank you.

Indeed, it should be `YearOfFormation` instead of `Description` inside the validator file and having the name mismatch was probably due to my running the generator as `ember g validator description`.

Since it's just an internal variable name, it doesn't really matter but of course it should be `YearOfFormation` if the generator is called with `year-of-formation`.

I slightly prefer to name the validator `year-of-formation` than `description` because that's what it validates. The band's description could have other validators (at least x characters) and this provides a nice chain of validators for properties that's easy to work with (for example, with an appropriate error message for each).
