### ISSUE TITLE
setTimeout or Ember.run.later

### ISSUE THREAD

**Issue by vikram-s-narayan** [balinterdi/rarwe-issues#71]
According to the documentation - http://emberjs.com/api/classes/Ember.run.html#method_later, 

it is recommended to use Ember.run.later rather than setTimeout.

So on page 217, should it be "Ember.run.later(function() { ..." instead of "setTimeout(function() { ..."?

Edit: I also see this thread where some concerns have been expressed about run.later - https://github.com/emberjs/ember.js/issues/3008#issuecomment-73246784)

So ... maybe it is still better to use setTimeout?

Thanks again ... The book truly rocks!

**Comment by balinterdi** [comment]
That's exactly the issue I ran into when developing an Ember app (you can even see my comment) and I'm thus wary of using `Ember.run.later`. That said, I might try it again today to see if the situation has improved but the code snippet in the book is totally temporary and only serves demo purposes so I would leave it as it is in order to not having to explain another concept.
